language: python
virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get install -qq python-numpy python-scipy
python:
  - "2.7"
script: nosetests
script:  "python setup.py develop && nosetests -w test/"
